import { OffersType } from '../types/cards';

export const offers : OffersType = [
  {
    city: 'Paris',
    cards: [
      {
        'id': 0,
        'title': 'Super Hotel in Saint-Petersburg',
        'price': '999',
        'imgSrc': 'https://placekitten.com/260/200',
        'type': 'apartment',
        'rating': 3,
        'isFavorite': false,
        'isPremium': true,
      },
      {
        'id': 1,
        'title': 'Super Hotel in Ekaterinburg',
        'price': '222',
        'imgSrc': 'https://placekitten.com/260/200',
        'type': 'apartment',
        'rating': 1,
        'isFavorite': true,
        'isPremium': true,
      },
      {
        'id': 2,
        'title': 'Super Hotel in Moscow',
        'price': '333',
        'imgSrc': 'https://placekitten.com/260/200',
        'type': 'apartment',
        'rating': 5,
        'isFavorite': false,
        'isPremium': false,
      },
      {
        'id': 3,
        'title': 'Super Hotel in Samara',
        'price': '444',
        'imgSrc': 'https://placekitten.com/260/200',
        'type': 'room',
        'rating': 2,
        'isFavorite': false,
        'isPremium': true,
      },
    ],
  },
  {
    city: 'Cologne',
    cards: [
      {
        'id': 0,
        'title': 'Super Hotel in Saint-Petersburg',
        'price': '999',
        'imgSrc': 'https://placekitten.com/260/201',
        'type': 'apartment',
        'rating': 3,
        'isFavorite': false,
        'isPremium': true,
      },
      {
        'id': 1,
        'title': 'Super Hotel in Ekaterinburg',
        'price': '222',
        'imgSrc': 'https://placekitten.com/260/201',
        'type': 'apartment',
        'rating': 1,
        'isFavorite': true,
        'isPremium': true,
      },
      {
        'id': 2,
        'title': 'Super Hotel in Moscow',
        'price': '333',
        'imgSrc': 'https://placekitten.com/260/201',
        'type': 'apartment',
        'rating': 5,
        'isFavorite': false,
        'isPremium': false,
      },
      {
        'id': 3,
        'title': 'Super Hotel in Samara',
        'price': '444',
        'imgSrc': 'https://placekitten.com/260/201',
        'type': 'room',
        'rating': 2,
        'isFavorite': false,
        'isPremium': true,
      },
    ],
  },
  {
    city: 'Brussels',
    cards: [
      {
        'id': 0,
        'title': 'Super Hotel in Saint-Petersburg',
        'price': '999',
        'imgSrc': 'https://placekitten.com/260/202',
        'type': 'apartment',
        'rating': 3,
        'isFavorite': false,
        'isPremium': true,
      },
      {
        'id': 1,
        'title': 'Super Hotel in Ekaterinburg',
        'price': '222',
        'imgSrc': 'https://placekitten.com/260/202',
        'type': 'apartment',
        'rating': 1,
        'isFavorite': true,
        'isPremium': true,
      },
      {
        'id': 2,
        'title': 'Super Hotel in Moscow',
        'price': '333',
        'imgSrc': 'https://placekitten.com/260/202',
        'type': 'apartment',
        'rating': 5,
        'isFavorite': false,
        'isPremium': false,
      },
      {
        'id': 3,
        'title': 'Super Hotel in Samara',
        'price': '444',
        'imgSrc': 'https://placekitten.com/260/202',
        'type': 'room',
        'rating': 2,
        'isFavorite': false,
        'isPremium': true,
      },
    ],
  },
  {
    city: 'Amsterdam',
    cards: [
      {
        'id': 0,
        'title': 'Super Hotel in Saint-Petersburg',
        'price': '999',
        'imgSrc': 'https://placekitten.com/260/203',
        'type': 'apartment',
        'rating': 3,
        'isFavorite': false,
        'isPremium': true,
      },
      {
        'id': 1,
        'title': 'Super Hotel in Ekaterinburg',
        'price': '222',
        'imgSrc': 'https://placekitten.com/260/203',
        'type': 'apartment',
        'rating': 1,
        'isFavorite': true,
        'isPremium': true,
      },
      {
        'id': 2,
        'title': 'Super Hotel in Moscow',
        'price': '333',
        'imgSrc': 'https://placekitten.com/260/202',
        'type': 'apartment',
        'rating': 5,
        'isFavorite': false,
        'isPremium': false,
      },
      {
        'id': 3,
        'title': 'Super Hotel in Samara',
        'price': '444',
        'imgSrc': 'https://placekitten.com/260/200',
        'type': 'room',
        'rating': 2,
        'isFavorite': false,
        'isPremium': true,
      },
    ],
  },
  {
    city: 'Hamburg',
    cards: [
      {
        'id': 0,
        'title': 'Super Hotel in Saint-Petersburg',
        'price': '999',
        'imgSrc': 'https://placekitten.com/260/201',
        'type': 'apartment',
        'rating': 3,
        'isFavorite': false,
        'isPremium': true,
      },
      {
        'id': 1,
        'title': 'Super Hotel in Ekaterinburg',
        'price': '222',
        'imgSrc': 'https://placekitten.com/260/202',
        'type': 'apartment',
        'rating': 1,
        'isFavorite': true,
        'isPremium': true,
      },
      {
        'id': 2,
        'title': 'Super Hotel in Moscow',
        'price': '333',
        'imgSrc': 'https://placekitten.com/260/203',
        'type': 'apartment',
        'rating': 5,
        'isFavorite': false,
        'isPremium': false,
      },
      {
        'id': 3,
        'title': 'Super Hotel in Samara',
        'price': '444',
        'imgSrc': 'https://placekitten.com/260/204',
        'type': 'room',
        'rating': 2,
        'isFavorite': false,
        'isPremium': true,
      },
    ],
  },
  {
    city: 'Dusseldorf',
    cards: [
      {
        'id': 0,
        'title': 'Super Hotel in Saint-Petersburg',
        'price': '999',
        'imgSrc': 'https://placekitten.com/260/201',
        'type': 'apartment',
        'rating': 3,
        'isFavorite': false,
        'isPremium': true,
      },
      {
        'id': 1,
        'title': 'Super Hotel in Ekaterinburg',
        'price': '222',
        'imgSrc': 'https://placekitten.com/260/199',
        'type': 'apartment',
        'rating': 1,
        'isFavorite': true,
        'isPremium': true,
      },
      {
        'id': 2,
        'title': 'Super Hotel in Moscow',
        'price': '333',
        'imgSrc': 'https://placekitten.com/260/199',
        'type': 'apartment',
        'rating': 5,
        'isFavorite': false,
        'isPremium': false,
      },
      {
        'id': 3,
        'title': 'Super Hotel in Samara',
        'price': '444',
        'imgSrc': 'https://placekitten.com/260/200',
        'type': 'room',
        'rating': 2,
        'isFavorite': false,
        'isPremium': true,
      },
    ],
  },
];
